import { Share, Platform } from 'react-native';
import * as Clipboard from 'expo-clipboard';
import { showAlert } from './alert';
import type { Task, Participant, Settlement } from '../types/database';

export function buildExpenseSummary(
  planTitle: string,
  expenses: Task[],
  participants: Participant[],
  settlements: Settlement[],
  totalSpent: number,
): string {
  const participantMap = new Map(participants.map((p) => [p.id, p]));

  let text = `📊 Expense Summary: "${planTitle}"\n`;
  text += `${'═'.repeat(36)}\n\n`;
  text += `👥 ${participants.length} people · ₹${totalSpent.toLocaleString('en-IN')} total\n\n`;

  // Per-person spending
  text += `💳 Expenses:\n`;
  for (const exp of expenses) {
    const payer = participantMap.get(exp.expense_paid_by ?? exp.assigned_to ?? exp.created_by);
    text += `  • ${exp.title} — ₹${(exp.expense_amount ?? 0).toLocaleString('en-IN')}`;
    if (payer) text += ` (paid by ${payer.name})`;
    text += '\n';
  }

  if (settlements.length > 0) {
    text += `\n💸 Settlements:\n`;
    for (const s of settlements) {
      text += `  • ${s.from.name} owes ${s.to.name} → ₹${s.amount.toLocaleString('en-IN')}\n`;
    }
  }

  text += `\n— Generated by Whodo (whodo.space)`;
  return text;
}

export async function shareExpenseSummary(summary: string) {
  if (Platform.OS === 'web') {
    if (navigator.share) {
      try {
        await navigator.share({ text: summary });
        return;
      } catch {}
    }
    await navigator.clipboard.writeText(summary);
    showAlert('Copied!', 'Expense summary copied to clipboard.');
    return;
  }

  try {
    await Share.share({ message: summary });
  } catch {
    await Clipboard.setStringAsync(summary);
    showAlert('Copied!', 'Expense summary copied to clipboard.');
  }
}
